# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

menu:
- {name: 'About',   url: 'about.html'}
- {name: 'Archives', url: 'archives.html'}
- {name: 'Contact', url: 'contact.html'}

social:
- {title: 'GitHub', link: 'https://www.github.com/seasonedfish', svg: "github.svg"}
- {title: 'Email', link: 'mailto:f.sun@wustl.edu', svg: "envelope-solid.svg"}
- {title: 'RSS feed', link: '/feed.xml', svg: "square-rss-solid.svg"}
- {title: 'LinkedIn', link: 'https://www.linkedin.com/in/fisher-sun/', svg: "linkedin.svg"}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'
