# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

menu:
- {name: 'About',   url: 'about.html'}
- {name: 'Archives', url: 'archives.html'}
- {name: 'Contact', url: 'contact.html'}

social:
- {title: 'GitHub', link: 'https://www.github.com/pyjamafish'}
- {title: 'Email', link: 'mailto:fisher521.fs@gmail.com'}
- {title: 'RSS Feed', link: '/feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'
